name: GCC Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_CONAN_CLASS: "MathglConan"
  SINTEF_REFERENCE: "mathgl*"
  SINTEF_LIBNAME: "mathgl2"
  CONAN_UPLOAD: "https://api.bintray.com/conan/sintef-ocean/conan"
  CONAN_PASSWORD_SINTEF: ${{ secrets.BINTRAY_API_KEY }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.BINTRAY_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-with-gcc:
    name: Conan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [63, 7, 8, 9]
        build_type: [Debug, Release]
        option_shared: [shared=True, shared=False]
        option_qt5: [qt5=False]
        os: [ubuntu-20.04]
        exclude:
          - compiler_version: 6
            option_qt5: qt5=True
            # qt 5.15 did not compile with gcc 6
    container:
      image: conanio/gcc${{ matrix.compiler_version }}
      options: -u 0
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo pip3 install --upgrade setuptools pip
          sudo pip3 install conan requests
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD} --insert 0
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan --insert 0
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.libcxx=libstdc++11 \
            -o ${SINTEF_LIBNAME}:${{ matrix.option_shared }} \
            -o ${SINTEF_LIBNAME}:${{ matrix.option_qt5 }} \
            -b missing -b outdated . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 5 --retry-wait 20 --force
      - name: Bintray info
        run: |
          python3 bintray.py ${SINTEF_CONAN_CLASS} \
            ${CONAN_LOGIN_USERNAME_SINTEF} ${CONAN_PASSWORD_SINTEF}
